version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8	
  post_build:
    commands:
      #- unzip *.zip
      - mvn install && mvn package
      - mv target/hello-world-war-1.0.0.war target/hello-world.war
artifacts:
  files:
    - target/*
    #- target/hello-world.war
    #- .ebextensions/**/*
  #base-directory: 'target'
  discard-paths: yes
