version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8	
  post_build:
    commands:
      - mvn package #install #&& mvn package
      #- mv target/hello-world-war-1.0.0.war target/ROOT.war
      - cd target
      - jar -cvf hello.war META-INF WEB-INF index.jsp
artifacts:
  files:
    - hello.war
    - ROOT.war
    #- target/hello-world-war-1.0.0
    #- .ebextensions/**/*
  base-directory: 'target'
  discard-paths: yes
