version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8	
  post_build:
    commands:
      - mvn install && mvn package
      #- mv target/hello-world-war-1.0.0.war target/ROOT.war
      - cd target
      - rm -rf * !(hello-world-war-1.0.0)     
      - jar -cvf hello.war .
artifacts:
  files:
    - hello.war
    #- ROOT.war
    #- target/hello-world-war-1.0.0
    #- .ebextensions/**/*
  base-directory: 'target'
  discard-paths: yes
